version: '2.1'

volumes:
  pg-master-data:
    driver: "${VOLUME_DRIVER}"
  pg-slave-data:
    driver: "${VOLUME_DRIVER}"
networks:
  postgres-network:
services:
  pg-master:
    image: xingjiudong/postgres-replication:${POSTGRES_VERSION}
    restart: always
    cpu_quota: 90000
    mem_limit: 3000M
    memswap_limit: -1
    volumes:
     - pg-master-data:/var/lib/postgresql/data
    logging:
      driver: "journald"
    dns:
     - ${DNS_SERVER}
    ports:
     - "5432"
    networks:
     - postgres-network
    environment:
     - affinity:container!=*pg*
     - constraint:volume.driver==${VOLUME_DRIVER}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - PGDATA=/var/lib/postgresql/data/pgdata
  pg-slave:
    image: xingjiudong/postgres-replication:${POSTGRES_VERSION}
    restart: always
    cpu_quota: 90000
    mem_limit: 3000M
    memswap_limit: -1
    volumes:
     - pg-slave-data:/var/lib/postgresql/data
    logging:
      driver: "journald"
    dns:
     - ${DNS_SERVER}
    ports:
     - "5432"
    networks:
     - postgres-network
    depends_on:
     - "pg-master"
    environment:
     - affinity:container!=*pg*
     - constraint:volume.driver==${VOLUME_DRIVER}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - PGDATA=/var/lib/postgresql/data/pgdata
     - REPLICATE_FROM=pg-master

